/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TokensTTS */

#ifndef _Included_TokensTTS
#define _Included_TokensTTS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TokensTTS
 * Method:    getVoiceToken
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_daxclr_ext_TokensTTS_getVoiceToken
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
