/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class QuadmoreSR */

#ifndef _Included_QuadmoreSR
#define _Included_QuadmoreSR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     QuadmoreSR
 * Method:    TakeDictation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_daxclr_ext_QuadmoreSR_TakeDictation
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
